name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: true
        default: "true"

defaults:
  run:
    shell: bash

jobs:
  Make:
    runs-on: ubuntu-latest
    name: Make ${{matrix.work}} ${{matrix.arch}}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Sync firmware Upload FTP
        id: ftpfirmware
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: "v0.ftp.upyun.com"
          username: "mofeng64/wind-openwrt"
          password: ${{ secrets.FTP_PASSWOD }}
          local-dir: "targets/"
          server-dir: "upyun/"
          dangerous-clean-slate: true

      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: "v0.ftp.upyun.com"
          user: "mofeng64/wind-openwrt"
          password: ${{ secrets.FTP_PASSWOD }}
          localDir: "targets/"
          remoteDir: "test"
          options: "--delete --asci"