name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: true
        default: "true"

defaults:
  run:
    shell: bash

jobs:
  Make:
    runs-on: ubuntu-latest
    name: Make ${{matrix.work}} ${{matrix.arch}}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: ls file
        run: |
          pwd
          date
          ls -lah targets/
      - name: Sync firmware Upload FTP
        id: ftpfirmware
        uses: MitchWind/ftp-deploy@master
        with:
          server: "v0.ftp.upyun.com"
          username: "mofeng64/wind-openwrt"
          password: ${{ secrets.FTP_PASSWOD }}
          ssl_allow: true
          local_dir: "targets"
          server_dir: "test"
          options: " --parallel=8 --ignore-time"
          delete: true
          debug: true
          # use_mlsd: true
          # use_mdtm: false
      # - name: Deploy
      #   uses: saltbo/uptoc@master
      #   with:
      #     driver: qiniu
      #     region: us-north-1
      #     bucket: windopenwrt
      #     exclude: .git
      #     dist: targets
      #     saveroot: openwrt
      #   env:
      #     UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_AK }}
      #     UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_SK }}
