name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: true
        default: "true"

defaults:
  run:
    shell: bash

jobs:
  Make:
    runs-on: ubuntu-latest
    name: Make ${{matrix.work}} ${{matrix.arch}}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: ls file
        run: |
          pwd
          date
          ls -lah targets/

      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - run: |
          npm install

      - name: Sync firmware Upload FTP
        id: ftpfirmware
        uses: MitchWind/ftp-deploy@master
        with:
          server: "v0.ftp.upyun.com"
          username: "mofeng64/wind-openwrt"
          password: ${{ secrets.FTP_PASSWOD }}
          ssl_allow: true
          local_dir: "targets"
          server_dir: "test"
          options: " --parallel=8 "
          delete: true
          debug: false
          use_mlsd: false
          use_mdtm: true
  Test:
    runs-on: ubuntu-latest
    needs: Make
    if: ${{ always() }}
    name: test
    steps:
      - name: 测试
        run: |
          echo "我只是测试错误后强制执行"
      #清理
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day'

      # - name: Deploy
      #   uses: saltbo/uptoc@master
      #   with:
      #     driver: qiniu
      #     region: us-north-1
      #     bucket: windopenwrt
      #     exclude: .git
      #     dist: targets
      #     saveroot: openwrt
      #   env:
      #     UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_AK }}
      #     UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_SK }}
